### ISSUE TITLE
Create preview (testsresults 1 + 2)

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#105]
**Story:** As a user I want to see a preview of my ad, before it will be published, in order to check the content and correct it if necessary.

_Acceptance Criteria_
- [x] AC1: all registered information is visible
- [x] AC2: Button [Back] is available
- [x] AC3: If [Back] button has been used, all previous puted information is available on the creation page -> story #106
- [x] AC4: Button [Publish] is available
- [x] AC5: If [Publish] button has been used, the system store the data and show success message. User will be navigate to the homepage.

Pictures are not part of this story

Precondition: 
- Design story #88 
- Create room ad #33 (implemented, archived)
- #63 should be implemented before (impact on the estimation)
-------
DoD

 - [x] Story is tested against acceptance criteria
 - [x] Unit test should be passed
 - [x] Integration test is done ( if applicable)
 - [x] Non-functional requirements are met
 - [x] Story ok-ed by Product Owner
 - [x] Peer Code Review performed
- [x]  Any configuration or build changes documented

**Comment by akrguda** [comment]
The first version was installed on INT. When I was testing it, I found some errors that do not fulfill the ACA. That is the reason the ticket get back to the stat "to do". The are documented in the following comments.

**Comment by akrguda** [comment]
After the data was entered the "preview" button was used. 




1. The title could be bold and bigger 
2. Both Categories show the functionname and not the content of the function
3. The date is not as usualy in german format 10.10.2022
4. Möbiliert shows the value and not the checkbox as it was on the enterform
5. Befristet shows the value and not the checkbox as it was on the enterform
6.

**Comment by akrguda** [comment]
The developer left the project marketplace and therefore I can not sent the request for correcting to the origin developer anymore. So this tickets is free for anybody who wants to fix the docmented problems.

**Comment by akrguda** [comment]
There was a second ticket with the same topic (Ticket https://github.com/AkrosAG/Akros-Marketplace/issues/106). In this ticket are also some information about the navigation and is redundant. This is the reason Ticket 106 was closed.

**Comment by akrguda** [comment]
As I was talking with Sereno, I showed him the application. In this Software-Demonstration I noticed, that the Software does not work with the new part describted above. So this ticket gets back to "to do" so that a developer can analyse the problem and fixe the errors and we can insert new ads.

**Comment by LanaKast** [comment]
AC5 funktioniert teilweise und kann noch nicht akzeptiert werden. @Atanasov-AA 
navigation zu Home fehlt.

**Comment by Dummylearners** [comment]
Retested case

@LanaKast @TimmyAeberli 

The fields of the tickets are functioning accordingly. Only Display of Images are not on display during preview. 
If the inserted images in preview are not programmed, could the case, the images are not in display here in preview.

Test environment: Firefox Browser
Test OS: Windows

Test Steps:

1. Open site and login
2. Click to "Alle Anzeige"
3. Filled all the required fields
4. Insert JPG images
5. Click to Preview

Pre-condition: all fields of "Alle Anzeige" work correctly
Expected test result: All the field details and images may be shown in Preview.
Post test result: Inserted images are not shown in Preview before publishing the advertisement.

TEST FAIL

Screenshot of test result:

![Image](https://user-images.githubusercontent.com/117288240/215801556-0206e206-e97d-4261-8ebe-2e14bb6d1edb.png)

**Comment by Dummylearners** [comment]
Adding comment for above test case, Images were inserted before clicking "Preview/Veröffenlich" button. Thanks.


![Image](https://user-images.githubusercontent.com/117288240/215807167-2c45ea34-4d98-4eb8-bbe8-0f6761d10aff.png)

**Comment by Dummylearners** [comment]
Observation-

- As mentioned also in #63, under "Eine Anzeige erstellen"  Zimmer is auto selected.
- Field doesn't show any sign or text to change the selection from drop down menu according to the requirement of publishing the Apartment or any Parkplatz until one click manually to change the accommodation type. Is this is build feature?

@LanaKast @TimmyAeberli @Atanasov-AA 

![Image](https://user-images.githubusercontent.com/117288240/215809323-471c4a47-64bc-4087-921c-307dfbe87692.png)

**Comment by Dummylearners** [comment]
Observation 2:

- Under **Unterkünfte** "Zimmer* is selected for new advertisement.
- After Clicking Preview Button, the type of filled Advertisement, Preview of Zimmer may show/mention.
- This Field type is not shown in preview.

@LanaKast @TimmyAeberli

**Comment by TimmyAeberli** [comment]
okayed by PO
