### ISSUE TITLE
Cancel ad creation

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#111]
**Story:** As a user I want to have a possibility to cancel ad creation at any point of time, so that no data has been saved.

_Acceptance criteria:_
- [x] AC1: The cancelation is possible on each page (on creation page and preview page)
- [x] AC2: No data is saved after cancelation
- [ ] AC3: Optional: we discused the possibilty about renaming the button and show a message (post specification, see comment later one)

consider aborting here #105 
-----
DoD

- [x] Story is tested against acceptance criteria
- [x]  Unit test should be passed
- [x] Integration test is done ( if applicable)
- [x]  Non-functional requirements are met
- [x]  Story ok-ed by Product Owner
- [x] Peer Code Review performed
- [x] Any configuration or build changes documented

**Comment by TimmyAeberli** [comment]
Vorschlag für Test-Case-Splitting: 



![Image](https://user-images.githubusercontent.com/41478805/204283704-12744b81-60f5-4ba3-9558-df9af7e5e360.png)

**Comment by TimmyAeberli** [comment]
Testing done on 29.11.22:

- [ ] passed

**Comment by Dummylearners** [comment]
Story can not be tested because search result is not working.


![Image](https://user-images.githubusercontent.com/117288240/205635224-35b90bc7-a1e1-45c9-9999-7facafe45b56.png)

@fingeririna @akrguda @TimmyAeberli

**Comment by Dummylearners** [comment]
How I can raise bug here?
@akrguda

**Comment by akrguda** [comment]
Open a new ticket and write down what the bug is. Set the state to "ready to refinment" and we will talk about it in the backlog meeting. 

@Dummylearners 
@TimmyAeberli

**Comment by akrguda** [comment]
Maybe we change the name of the "zurück" button to "abbrechen" (equal in english) and we may show a message about "do you realy want the cancel the ad".

**Comment by Dummylearners** [comment]
agreed. @akrguda

**Comment by akrguda** [comment]
There is a second ticket about this topic 

https://github.com/AkrosAG/Akros-Marketplace/issues/257

**Comment by LanaKast** [comment]
Test & Testprotokoll needs to be carried out for this ticket @sereno77 , thank you

**Comment by sereno77** [comment]
Sereno, 17.01. 2023: Testing done, test document done, Test passed / ok

**Comment by TimmyAeberli** [comment]
Okayed by PO
