### ISSUE TITLE
Search for apartment or house requests

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#141]
**Story:** As a user I want to be able to search for apartment or hous requests by specifying some selection criteria, in order to quickly find requests for apartment or house.

[https://akrosag-my.sharepoint.com/❌/g/personal/aebeti_akros_ch/EUUylLx0THdDjM8-1eXp6doBsTIvLdceBlsbUg8oZDKEeA](https://akrosag-my.sharepoint.com/:x:/g/personal/aebeti_akros_ch/EUUylLx0THdDjM8-1eXp6doBsTIvLdceBlsbUg8oZDKEeA)

_Acceptance criteria:_
- [x] AC1: In the category Accomodation I select Apartment & Requests and get the search criteria for apartment request as in excel above.
- [x] AC2: In the category Accomodation I select House & Requests and get the search criteria for apartment requests as in excel above.
- [x] AC3: I select multiple criteria and get the results for apartment requests accordingly
- [x] AC4: I select multiple criteria and get the results for house requests accordingly
----------------------------------
Definition of Done
- [x] Story is tested against acceptance criteria
- [ ] Unit test should be passed
- [ ] Integration test is done ( if applicable)
- [ ] Non-functional requirements are met
- [ ] Story ok-ed by Product Owner
- [ ] Peer Code Review performed
- [ ] Any configuration or build changes documented
- [ ] Any database changes are documented [Database](https://github.com/AkrosAG/Akros-Marketplace/wiki/Database)

**Comment by Dummylearners** [comment]
- This user story is part of Epic. (Please see attached image)
- AC from 1 to 4 is tested by someone on 28.12.2022. All test Pass. But Tester name is missing in Test Document.
- In DoD only > Story is tested against acceptance criteria, rest is part of product owner.

@LanaKast @TimmyAeberli 

![Image](https://user-images.githubusercontent.com/117288240/210553860-f7b2c55f-5e75-41d1-aa61-7c594870ea4e.png)

**Comment by Dummylearners** [comment]
Tested by @sereno77
