### ISSUE TITLE
Search for parking space

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#143]
**Story:** As a user I want to be able to search for parking space offers or requests by specifying some selection criteria, in order to quickly find a parking space offer or somebody who needs the parking space.

[https://akrosag-my.sharepoint.com/❌/g/personal/aebeti_akros_ch/EUUylLx0THdDjM8-1eXp6doBsTIvLdceBlsbUg8oZDKEeA](https://akrosag-my.sharepoint.com/:x:/g/personal/aebeti_akros_ch/EUUylLx0THdDjM8-1eXp6doBsTIvLdceBlsbUg8oZDKEeA)

_Acceptance criteria:_
- [x] AC1: In the category Accomodation I select Parking Space & Offers and get the search criteria for a parking space offer as in excel above.
- [x] AC2: In the category Accomodation I select Parking Space & Requests and get the search criteria for parking space request as in excel above.
- [x] AC3: Search without limitations gives the results of parking space offer ads accordingly
- [x] AC4: Search with multiple limitations gives the results of parking space offer ads accordingly
- [x] AC5: Search without limitations gives the results of parking space request ads accordingly
- [x] AC6: Search with multiple limitations gives the results of parking space request ads accordingly
----------------------------------
Definition of Done
- [x] Story is tested against acceptance criteria
- [x] Unit test should be passed
- [x] Integration test is done ( if applicable)
- [x] Non-functional requirements are met
- [x] Story ok-ed by Product Owner
- [x] Peer Code Review performed
- [x] Any configuration or build changes documented
- [x] Any database changes are documented [Database](https://github.com/AkrosAG/Akros-Marketplace/wiki/Database)

**Comment by Dummylearners** [comment]
Two AC 1 and 3 are Pass.

**Comment by sereno77** [comment]
Sereno, 28.12.2022: Testing done, test document done, Test passed / ok

**Comment by TimmyAeberli** [comment]
Okayed by PO
