### ISSUE TITLE
Create Definition of Ready for the new Dev Team

### ISSUE THREAD

**Issue by TimmyAeberli** [AkrosAG/Akros-Marketplace#159]
As a Dev I want to know exactly what tickets (Story, Epics) meet the standard to be included in the sprint backlog, so that I can reject inconsistent or vague requirements BEFORE they come into the new sprint.

**DoR:**

- [ ]  There is a high level technical solution for this story. If not, a research ticket has been created and should be solved before this story.
- [ ]  The story has no dependencies or the dependencies are clearly identified and a story has been created for them.
- [ ]  The story has at least one acceptance criteria.
- [ ]  The story is estimated (in story points).

~~It makes sense to define DOR, ACA, DOD for each tickets because every ticket have different requirements and therefore those got to be described in the ticket to give the ticket the chance to be done in best quality.~~

In a meeting (Daniel / Timmy) we descided that we talk about this topic in a team meeting. So the team knows about those elements (DOR, ACA, DOD) in tickets, will describe it when they write new tickets and use it to check the own work before a ticket get the next state. It is good, when the members of the team keep this structure in mind, then they know to use it for define a ticket and it is helpful to check the own work about fullfilled all ACA. 

Output from Workshop of January 24th, 2023: the DoR and DoD are fixed across all issue types and individual tickets. The PBIs are to be filled with DoR and DoD (in addition to the Acceptance Criteria). However, individual checkboxes can be deactivated by using the double tilde (~ ~) before and after the respective line, i.e. ~~[] b) Jede Story ist maximal 3 Tage gross~~

**Comment by pestadieu** [comment]
Below is a first draft of a definition of ready. Feel free to add your comments:

- [ ] There is a high level technical solution for this story. If not, a research ticket has been created and should be solved before this story.
- [ ] The story has no dependencies or the dependencies are clearly identified and a story has been created for them.
- [ ] The story has at least one acceptance criteria.
- [ ] The story is estimated (in story points).

**Comment by akrguda** [comment]
DoR (defintion of ready), Acceptance Criteria and DoD (definitin of done) is defined and we work now on every ticket we set in the stat "ready to dev". 

Example: 
https://github.com/AkrosAG/Akros-Marketplace/issues/133

This is the reason this ticket gets the stat "PO test"

**Comment by akrguda** [comment]
There are some questions about how to handle DoR and DoD. We wait to the answers of Marco.

**Comment by TimmyAeberli** [comment]
Ich kenne die DoR und auch DoD als generelle Vereinbarung und nicht explizit pro Story. Ich erachte es jedoch auch als sinnvoll dies jeweils pro Story auch anpassen zu können, da es allenfalls nicht sinnvoll ist jeden einzelnen Punkt zu erfüllen, von dem her kann man das Anpassen.

Wichtig ist ja das Ziel der DoR --> das Team hat alles, damit sie ihre Arbeiten im Sprint erledigen können.

Aus der Praxis sehe ich auch, dass die DoR zu beginn relativ umfangreich ist und dann zusammen mit der Team Maturität dann immer kleiner wird (ganz entgegen des Verlaufes einer DoD).

We will leave our DoD as a case-by-case definition. This way we can gain experience with it.

**Comment by akrguda** [comment]
The ticket state was set to closed after the infos from Marco and got the state "in progress". I will ask Timmy what we want to do with tihs ticket. So I reopened it and set it on the last known state "PO test" for the discusion after Timmy is back at work.

**Comment by balsih** [comment]
Could you please update the corresponding [confluence-wiki-page](https://wiki.akros.ch/pages/viewpage.action?pageId=116819943) as soon as the ticket is completed?

**Comment by balsih** [comment]
@TimmyAeberli do you need help here? Can I support you?

**Comment by TimmyAeberli** [comment]
Done
