### ISSUE TITLE
Restrict to enter numeric values in the input fields.

### ISSUE THREAD

**Issue by asiday** [AkrosAG/Akros-Marketplace#168]
**Story:** As a user I want to give the price in the "to price" - search field and "from Size" - search field in number format. Restrict a user to enter only numeric values in the input fields  "to price" and "from Size". 

_Acceptance criteria:_
- [x] AC 1: Predefine no default values.
- [x] AC 2: Match the search results to the search query with price or size.

_Task:_
- [x] Search for apartment or house offers -> Story https://github.com/AkrosAG/Akros-Marketplace/issues/28 should be implement before

----------------------------------
Definition of Done:
- [ ] Story is tested against acceptance criteria
- [ ] Unit test should be passed
- [ ] Integration test is done ( if applicable)
- [ ] Non-functional requirements are met
- [ ] Story ok-ed by Product Owner
- [ ] Peer Code Review performed
- [ ] Any configuration or build changes documented
- [ ] Any database changes are documented [Database](https://github.com/AkrosAG/Akros-Marketplace/wiki/Database)

**Comment by Dummylearners** [comment]
Wanted to retest, site is not working, there is no search field working. " Alle Anzeigen" "Eine Anzeige Erstellen" @LanaKast @asiday @sereno77

**Comment by Dummylearners** [comment]
Test Environment: Firefox Web browser
Test OS: Windows

Test case 1
Test steps

Open Site
Under Unterkünfte/Accommodations, click Angebote (is auto selected)
Choose Haus/house
In “Bis preis field type numeric value 10000
Click to Suche/Search button
Look for search result in next page

Pre-condition: Advertisement is already created with price value
Post result: Advertisement is on display with price value

Test Pass

Screenshot of test result:

![Image](https://user-images.githubusercontent.com/117288240/213533759-74d43315-6000-43d1-9c29-e84ee974266d.png)

**Comment by Dummylearners** [comment]
Anupama/ Test pass on 19.01.2023/ Test document updated/ OK

**Comment by TimmyAeberli** [comment]
Okayed by PO
