### ISSUE TITLE
Disable unused field "Radius (KM)" from the searchform

### ISSUE THREAD

**Issue by akrguda** [AkrosAG/Akros-Marketplace#172]
As PO I want to see and use fields that are in charge so every searchitems does work in the searchfunction and no "unused" fields can be selected. 

**DoR:**
- [ ] The software is stable and usable

Acceptance critera:

- [ ] In the version at 04. oct 2022 there is a field in the searchform called "Radois (KM)". The field is disabled and does not shows up in the searchform anymore till it is specified in a new ticket about to handle values in this field.

DoD:
- [ ] The field does not show up anymore and is therefore not reachable anymore
- [ ] The new version is installed on INT Environment and usable to all

**Comment by akrguda** [comment]
Example: 


![Image](https://user-images.githubusercontent.com/105440971/193828716-2dd5e425-ca83-4a16-9ea6-b13a595ac018.png)

**Comment by sereno77** [comment]
Sereno, 05.01.2023 : Testing done, test document done, Test passed / ok
