### ISSUE TITLE
Use KAFKA as a new technologie part in the project

### ISSUE THREAD

**Issue by akrguda** [AkrosAG/Akros-Marketplace#173]
As a stakeholder I want the dev team to analyse and use new technologies in the project so that the dev teams get improved on KAFKA

Remark: This ticket is at it's first definition just a kind of reminder that the stakeholder wants to see new technologies in use. In this case we do have to think about an useful use this technologie for the marketplace project. As soon we have a plan, we will define also the acceptance criteria and Dod. 

**DoR:**
- [ ] The team does have a plan how to use KAFKA in the marketplace. The usecase is clear and documented in this ticket
- [ ] We got a license to install KAFKA on our environment

**Acceptance critera:**

- [ ] 

**DoD:**
- [ ]

**Comment by Dummylearners** [comment]
Kafka is regarding server, thus this is not part of my task from testing point of view. You may assign to developer.  Thanks. @LanaKast
