### ISSUE TITLE
Monitoring the state of the application

### ISSUE THREAD

**Issue by akrguda** [AkrosAG/Akros-Marketplace#174]
As an administrator I want to know about the state of the marketplace application so I can check wheter it is working fine or we have issues that prevent the application for running or running with good performance. 

Remark: This ticket is at it's first definition just a kind of reminder that the stakeholder wants to see new technologies in use. In this case we do have to think about an useful software to monitor our application so we can check at every moment, if its working or if there are any issus to check. 

**DoR:**
- [ ] The team found a software to monitoring the application state 
- [ ] When we got a software selected and ready to use, we will define the acceptance criteria and DoD. 

**Acceptance critera:**

- [ ] 

**DoD:**
- [ ]

**Comment by LanaKast** [comment]
AC's and DoD wurden zu diesem Zeitpunkt nicht konsequent nachgeführt, sollte von PO angeschaut werden @TimmyAeberli
