### ISSUE TITLE
React, Enzyme Library for Unit Tests does not work

### ISSUE THREAD

**Issue by akrguda** [AkrosAG/Akros-Marketplace#176]
As a developer I want to test the software with React so that I can use React for automatic tests.

**DoR:** 

- [ ] The software is developed and ready for testing
- [ ] The software for doing React SW tests is installed and works

**Acceptance criteria (ACA):**

- [ ] The React is configured for testing purpose
- [ ] The tets of the developed software using React works and can be controlled for checking if the tests are working 
- [ ] The problems showed up on the infrastructure by Asida are solved and Asida can write / do the tests

**Dod:**

- [ ] We know, why the React software did not work on the infrastructure by Asida
- [ ] We got the knowhow how to do tests with React
- [ ] The documentation about installation, troubleshooting and using React is up to date

**Comment by TimmyAeberli** [comment]
out of scope
