### ISSUE TITLE
Data must be saved in table advertiser and related to it

### ISSUE THREAD

**Issue by akrguda** [AkrosAG/Akros-Marketplace#182]
_As a user I want that my ad (topic) is stored related to my user login (advertiser) so that I can see just my ad for working on it with the ticket._

- [x]  **Open Questions:**

- Is it possible to just have a n-to-n relationship between advertiser and topic? (Data Engineer -> Daniel)
   Answer: No, it's not necessary, as a user wants to be the only person to administer his ad (1 user, n topics)! 

**Implementation Suggestion:**
- Connect topic to advertiser but check for each user, whether an advertiser is already available.
- The check could occur as the user presses the button "veröffentlichen" (see screenshot).

<img width="961" alt="image" src="https://user-images.githubusercontent.com/41478805/199756779-c41ca58b-7d5c-440f-b019-92e200bf4939.png">

---------------
**DoR**
- [ ]  There is a high level technical solution for this story. If not, a research ticket has been created and should be solved before this story.
- [ ]  The story has no dependencies or the dependencies are clearly identified and a story has been created for them.
- [x]  The story has at least one acceptance criteria.
- [ ]  The story is estimated (in story points).

---------------

**Acceptance Criteria**

- [ ] **AC1:** For the specific user, the system checks whether there's already an advertiser created.
- [ ] **AC2:** In case an advertiser is already linked to the user, the new topic that's been created is connected to that advertiser.
- [ ] **AC3:** In case no advertiser is liked to the user, a new advertiser (advertiser id) is generated and linked to the new topic
- [ ] **AC4:** Each topic is linked to one and only one (n-1) advertiser which is liked to one user (Data is checked and written per profile)

---------------
**DoD**
- [ ] Data is checked and written per profile
- [ ] Advertisment is uniquely assignable to an advertiser
- [ ] Story is tested against acceptance criteria
- [ ] Unit test should be passed
- [ ] Integration test is done ( if applicable)
- [ ] Non-functional requirements are met
- [ ] Story ok-ed by Product Owner
- [ ] Peer Code Review performed
- [ ] Any configuration or build changes documented

**Comment by akrguda** [comment]
This is the database design for the changes. The changes are marked "yellow"



![Image](https://user-images.githubusercontent.com/105440971/196648635-be17c880-9c30-4ba6-a0b5-0150efeeff94.png)

**Comment by akrguda** [comment]
Please use the 

-  DoR (Definition of Ready) 
- ACA (Acceptance criteria)
- DoD (Definition of Done)

in the ticket

**Comment by akrguda** [comment]
In the refinment meeting 15th november 2022 the team has decided to proof the use of keycloak in tihs case. For this proposition we create the ticket 

to get the knowhow for using keycloak and the possibility to use keycloak in this ticket instead of the advertiser table.

**Comment by sereno77** [comment]
After a technical review with @Filipe-Inacio there were several findings: the AD is already stored with keycloak and there is no need that the exact same AD is stored on a additional data base. @Filipe-Inacio will create a new ticket in order to remove the existing ADs from the system.

**Comment by Filipe-Inacio** [comment]
According @sereno77 I have creating following ticket: https://github.com/AkrosAG/Akros-Marketplace/issues/255

**Comment by TimmyAeberli** [comment]
okayed by PO
