### ISSUE TITLE
Show my ads

### ISSUE THREAD

**Issue by balsih** [AkrosAG/Akros-Marketplace#184]
**Story**
*As an advertiser I want to see all the ads I created, in order to know what I created.*

**Preconditions**
- user is logged in

**Post-Conditions**
- changes are saved in the corresponding database tables

**Dependencies**
This story must be finished before [Story Nr. 185](https://github.com/AkrosAG/Akros-Marketplace/issues/185) and [Story Nr. 186](https://github.com/AkrosAG/Akros-Marketplace/issues/186) can be started

-----

**DoR**
- [ ] External dependencies are identified or eliminated
- [ ] Design (at least LoFi?)
- [ ] Has acceptance criteria
-----

**Acceptance Criteria**
- [ ] the user can see all the ads he created under "settings/my-ads". This could be implemented the same way as the component "search-results" inclusive the filter options. -> ![Image](https://user-images.githubusercontent.com/27404338/197139803-f10c0518-740c-45ad-af00-293eab250302.PNG)
- [ ] the user is able to click on an ad to see the full details of the ad as it is the case in the component "search-results-details"

-----
**DoD**
- [ ] Story is tested against acceptance criteria
- [ ] Unit test should be passed
- [ ] Integration test is done ( if applicable)
- [ ] Non-functional requirements are met
- [ ] Story ok-ed by Product Owner
- [ ] Peer Code Review performed
- [ ] Any configuration or build changes documented
- [ ] any database changes are documented [Database](https://github.com/AkrosAG/Akros-Marketplace/wiki/Database)

**Comment by balsih** [comment]
Because the "search-results" component is written in React and the "show-my-ads" in Angular, the map (see Mockup will not be build now. That way the coding will be accelerated. The map could be later introduced but for now it wouldn't be of big value for the user.

**Comment by akrguda** [comment]
Cool! Part one with "show" my ad works. Also the delete button is working. The button to update the ad is not implemented and the detail view is blocked (now scrolling in the page is enabled / blocked)

**Comment by sereno77** [comment]
Sereno, 23.12.2022: Testing done, test document done, Test passed / ok
