### ISSUE TITLE
Delete my ads

### ISSUE THREAD

**Issue by balsih** [AkrosAG/Akros-Marketplace#185]
**Story**
*As an advertiser I want to be able to delete some of my ads because I no longer want to offer something.*

**Preconditions**
- user is logged in

**Post-Conditions**
- changes are saved in the corresponding database tables

**Dependencies**
This story can be started after [Story Nr. 184](https://github.com/AkrosAG/Akros-Marketplace/issues/184) has been finished.

-----

**DoR**
- [x] External dependencies are identified or eliminated
- [x] Design (at least LoFi?)
- [x] Has acceptance criteria
-----

**Acceptance Criteria**
- [x] the user can see an delete icon below each of his ads in "settings/my-ads". This could look like this -> 
![Image](https://user-images.githubusercontent.com/27404338/197143823-bc5686b3-e8bf-4678-a302-a9472eb961d0.PNG)
- [x] the user is able to click on the delete icon of one of his ads and then the ads disappears from the GUI and the DB.
- [x] A modal/pop-up should be shown after hitting the delete button to confirm this action.

-----
**DoD**
- [x] Story is tested against acceptance criteria
- [x] Unit test should be passed
- [x] Integration test is done ( if applicable)
- [x] Non-functional requirements are met
- [x] Story ok-ed by Product Owner
- [x] Peer Code Review performed
- [x] Any configuration or build changes documented
- [x] any database changes are documented [Database](https://github.com/AkrosAG/Akros-Marketplace/wiki/Database)

**Comment by balsih** [comment]
Ideas for further user stories in this direction:
- we could allow the user to multi-select ads and delete them in bulk

**Comment by sereno77** [comment]
Sereno, 23.12.2022: Testing done, test document done, Test passed / ok
