### ISSUE TITLE
Search type radio button behaviour upon subcategory change + checkbox visual defect

### ISSUE THREAD

**Issue by Ayerbe88** [AkrosAG/Akros-Marketplace#200]
The radio button at the start of the search form, "Angebote/Anfragen", resets it's value when an option in the sub-category selector is changed. The value should persist when changing any other form values.

Small white border in the "(Nur) Möbiliert" checkbox should be removed.

![Image](https://user-images.githubusercontent.com/5686587/199518159-6d2ef664-8981-4b38-9764-0b920457aaf8.png)

DoR:

[] The software is in a stable conditions to reproduce the error
ACA (Acceptance criteria:):

[] AC1: "Angebote/Anfragen" does not change value when any other form values get modified
[] AC2: "(Nur) Möbiliert" checkbox does not show a white border (box-shadow) in the bottom 

DoD:

[] Dod1: The software on INT can be used with the correct behaviour and styles in the search form

**Comment by sereno77** [comment]
Sereno, 05.01.2023: Testing done, test document done, Test passed / ok

**Comment by TimmyAeberli** [comment]
PO okayed
