### ISSUE TITLE
Enable code scanning (vulnerabilities)

### ISSUE THREAD

**Issue by akrguda** [AkrosAG/Akros-Marketplace#214]
As a member of the development team I know how we can scan ower code about vulnerabilities so that we can improve the security and quality of our software project. 

**DoR:**
- [ ] A software developer is selected and confirmed to handle this ticket

**Acceptance Criteria:**
- [ ] AC1: An evalutation about which tool etc. can be used for this purpose
- [ ] AC2: The selected tool gets tested about usability in our project 
- [ ] AC3: The evaluated tool and how to use it is documented
- [ ] AC4: Check the different layers and tool to check the security. 

**DoD:**
- [ ] We got the knowhow how to improve the vulnerabilities
- [ ] With a demonstration about the roadmap, all members of the team knows what is to do next and how to handle it at work
- [ ] The next steps are cleary specified

**Comment by balsih** [comment]
**Tool-Optionen**
- https://www.sonarqube.org/downloads/ = Static Code Analysis for Java, C#, JavaScript, HTML, CSS and much more
- https://snyk.io/plans/ = Container- and IaC-Security

**Comment by asiday** [comment]
Please check the documentation for the local code analyse with SonarQube here https://wiki.akros.ch/display/TO/Code+Analysis+with+SonarQube
