### ISSUE TITLE
Search over all does not work anymore

### ISSUE THREAD

**Issue by akrguda** [AkrosAG/Akros-Marketplace#222]
As a user I want to see all ads so I use the button "alle anzeigen" but no results are shown. 

DoR: 

No DoR. It is a bug in the current software 

Aca:

- [ ] AC1: I can use the button "alle anzeigen" and all ads are shown on the search result page

DoD:

- [ ] Bug is fixed and all ads shows up on the search result page
- [ ] Software is tested with an other member of the team and checked in on INT

**Comment by akrguda** [comment]
examples: 

Button to test: 



![Image](https://user-images.githubusercontent.com/105440971/202196255-f67cfd80-d7f7-448b-946c-3a6f49fdc42e.png)


Results: 



![Image](https://user-images.githubusercontent.com/105440971/202196385-531ea0e1-a405-4d95-a454-d9d5820ef525.png)

**Comment by akrguda** [comment]
Asida solved the problem but we did not the root of the problem. Here is description: 

https://wiki.akros.ch/pages/viewpage.action?pageId=130449488

**Comment by Dummylearners** [comment]
![grafik](https://user-images.githubusercontent.com/117288240/204168654-0b1107b4-91da-45d6-a1b3-d0f9c1077efe.png)

**Comment by akrguda** [comment]
Sereno, 22.12.2022: Testing done, test document done, Test passed / ok

**Comment by LanaKast** [comment]
The ticket goes back to "in progress" until the root issue is found and fixed. @asiday @Dummylearners

**Comment by asiday** [comment]
The problem is solved. The cause was unsupported format of uploaded picture for new add.

_Steps to reproduce a problem:_
First, create a new Advertisement:
1.  Post your new Advertisement from the Home Page by pushing the button "Create an Add". 
2. On the newly opened page https://am-ui.azurewebsites.net/create fill in all necessary fields.
3. Upload a picture for your Advertisement. Click on "Builer hochladen".
4. ### Select a picture if **.jfif** format from your device/computer. 
5. Press preview button.
6. Save your Advertisement.

Second, search for all or some specific Advertisements:
1. Go to Home page. 
2. Click on "Search over all" button.

_Expected Result:_


![Image](https://user-images.githubusercontent.com/86468677/212265209-c479260d-ba86-4961-8a2b-7f9a72d87ebe.jpg)


_Actual Result:_


![Image](https://user-images.githubusercontent.com/86468677/212265263-28c36e8c-3db2-426b-bce2-e2cc97c95fe5.png)

**Comment by Dummylearners** [comment]
"Alle Anzeige" working. Noticed> All finished "Anzeigen" are shown 25 in numbers.

Bug Found! If you change under Angebote, from Zimmer to "Haus" or "Wohnung" or "Parkplatz" the total number of  specific search results comes to same results i.e 25 in total number .

By clicking the checkbox "Mobiliert" gives the same result, i.e total search results appear 25 in number.

Test Document is updated

@asiday @LanaKast

**Comment by Dummylearners** [comment]
Reopen ticket.

**Comment by Dummylearners** [comment]
Test Environment: Firefox Web browser

Test Steps


1. Open Site
2. Login
3. Under Angebote/ offers select House
4. Click to Suche/Search button

Test pass

Test result image>
![image](https://user-images.githubusercontent.com/117288240/213514074-4d7bcc08-8025-4bbf-9e97-319f331fa534.png)

**Comment by Dummylearners** [comment]
Anupama, 19.01. 2023: Testing done, test document done, Test passed / ok

**Comment by Dummylearners** [comment]
@asiday @LanaKast 
Repeated given solution steps, Result is not same as expected.

- Search for all topics and find the ID number of your topic. > Where to search and find ID?
- "Delete your topic using the ID >"Topic ID is 0 in Red?

Please check, if any step is missed out. Thanks

Screenshot 1.
<img width="274" alt="userID-0" src="https://user-images.githubusercontent.com/117288240/214452358-995ea8cc-5961-461c-97db-0819cc063a4c.png">
Screenshot 2.
![image](https://user-images.githubusercontent.com/117288240/214452720-c2f21e62-f810-424a-991f-f507a91a9223.png)

**Comment by asiday** [comment]
@Dummylearners 
The Screenshot 1 is an Example Value, it is not actual value.
To request all values from backend, please do not forgot to do this step:

Search for all topics and find the ID number of your topic.
Create a HTTP request [GET /topics/searches](https://am-marketplace-service.azurewebsites.net/swagger-ui/index.html#/topic-controller/_topicsSearchesGet) → Go to "GET /topics/searches" → Press the button "Try it out" → Press the button "Execute" → Find your advertisement.

The button "Try it out" is here:
![Image](https://user-images.githubusercontent.com/86468677/214514465-a566f9d3-ec18-4052-baeb-bb4536b98c20.jpg)

This is "Execute" button:
![Image](https://user-images.githubusercontent.com/86468677/214514845-8dc871e4-d9d1-43d9-81dc-d07ec23d75e0.jpg)

Now you can find all advertisements in response body: 
![Image](https://user-images.githubusercontent.com/86468677/214515309-e49f329e-93ab-49f9-a2bf-920f7ed8189d.jpg)

**Comment by Dummylearners** [comment]
False Topic Ids are deleted with false image formats

Now "Suche/Search" are working.
@asiday. Thank you for help.
@LanaKast

**Comment by Dummylearners** [comment]
Test Environment: Firefox
Test OS: Windows
Test Result: Pass

Repeat test steps to reproduce the pass results.

Anupama/Test Pass/ Test document updated/ 25.01.2023 @LanaKast 

Screenshot:


![Image](https://user-images.githubusercontent.com/117288240/214586836-1aa5ccba-76a3-4b8d-a6b7-3afdbf5fbabc.png)
