### ISSUE TITLE
New documentation pages in confluence review and refine

### ISSUE THREAD

**Issue by akrguda** [AkrosAG/Akros-Marketplace#248]
As a PO I want the new documentation in confluence is checked a second time and up to date. 

DoR: 

None

Aca:

- [ ] The new documentation structure (suggested and done by Simon) is checked about usable and old pages
- [ ] If the are still old pages (see: [Wiki](https://wiki.akros.ch/display/TO/Archive)) we will discuss them in the team and eliminate it as soon as possible

DoD:

- [ ] The new structure is reviewed at usabe and in use
- [ ] As fare we found old pages to eliminate we eliminated it

**Comment by balsih** [comment]
@sereno77 and @NathalieBandi do you need help here? Can I support you?

**Comment by sereno77** [comment]
@balsih Hi Simon, thanks for your support. We will have a meeting this afternoon about this ticket. In case we need some further infos or help I will contact you. Greets.

**Comment by NathalieBandi** [comment]
after a short call with @sereno77 and @balsih we finished the review of the documentation and moved some content in other sections and deleted the obsolete part (Archive).

**Comment by TimmyAeberli** [comment]
@NathalieBandi  @sereno77  Could you please prepare this as a short Demo for the Incubator Meeting tomorrow?

**Comment by sereno77** [comment]
Hello @TimmyAeberli yes I can quickly present the new confluence structure.
