### ISSUE TITLE
Create a new confluence page about team members and needs / wishes about education

### ISSUE THREAD

**Issue by akrguda** [AkrosAG/Akros-Marketplace#249]
As a Teammember I want to describe in the documentation center the education I want to do so I can improve my skills. 

DoR:

- [x] The position in the documentation area is defined and checked out with Simon so we keep the new structure as he was planing it

Aca: 

- [x] Ac1: The location of the new page is clear and works with the new documentation conept
- [x] Ac2: The structure of the new page is clear and builded in the new page (Structure name and education or education and names for example)

DoD:

- [x] We have a new page we can see, who wants to do which education

**Comment by akrguda** [comment]
Feedbak Simon: The new page goes under "skills and knowhow"

**Comment by TimmyAeberli** [comment]
Has been well perceived and influenced the product roadmap

**Comment by TimmyAeberli** [comment]
okayed by PO
