### ISSUE TITLE
Delete advertiser table and all references 

### ISSUE THREAD

**Issue by Filipe-Inacio** [AkrosAG/Akros-Marketplace#255]
As a member of the development team I don't want to save the data of an user twice. One time in the keycloak database and also in our own table. Therefore the advertiser table needs to be removed from the project.

DoR: 

- [x]  A software developer is selected and confirmed to handle this ticket.

Acceptance Criteria.

- [ ]  AC 1: The advertiser table is deleted form the database
- [ ]  AC 2: All references in the java code (Entity, repository, tests) are deleted

DoD:

- [ ]  The software is up to date
- [ ]  The software is installed on int

**Comment by Atanasov-AA** [comment]
In the database, there isn't a table advertiser. In the code, there aren't any advertiser entities. This ticket and ticket #182 must be closed. (19.01.2023) 
@LanaKast  I don't think that this can be QA tested, should I move both tickets directly to "In spring abgeschlossen"?
