### ISSUE TITLE
Scrum Rolle beschreiben

### ISSUE THREAD

**Issue by TimmyAeberli** [AkrosAG/Akros-Marketplace#256]
**Userstory:** As a new Team Member I'd like to see all the roles in the Team (with their respective responsiblities), so that I know with whom to talk and what to expect / deliver.

**Description:**
Please pick a role (your role) and read through the description and add missing details as you see fit.

**DoR:**

- [x] The team has been informed about the need to sepcify the roles 
- [x] An example is written in the necessary detail and can be referenced

Acceptance Criteria

- [x] Business Analysts role is described (per Example of the PO)
- [x] Designer role is described (per Example of the PO)
- [x] Product Owner role is described
- [x] Scrume Master role is described (per Example of the PO)
- [x] Software Engineer role is described (per Example of the PO)
- [x] Test Engineer role is described (per Example of the PO)

**Comment by TimmyAeberli** [comment]
![Image](https://user-images.githubusercontent.com/41478805/205305644-8c40129b-5b28-438a-b6e6-2eac81452a0b.png)

**Comment by TimmyAeberli** [comment]
@sereno77  offered to do the Business Analyst role description, thanks Sereno

**Comment by LanaKast** [comment]
**Acceptance Criteria: Designer role** cannot be fulfilled, as there are currently no Designers in the team.
