### ISSUE TITLE
Back Button on the Ad creation page isn't working

### ISSUE THREAD

**Issue by akrguda** [AkrosAG/Akros-Marketplace#257]
Environment / version: Test 

Description:  111
According to the story:  https://github.com/AkrosAG/Akros-Marketplace/issues/111 the ad creation should be cancelable also on the creation page. The button "ZURÜCK" at the bottom of the page isn't working.

Note: the priority of this bug is low, because the page is workable with the  "ZURÜCK" button in the top left corner of the page.

Reproduction steps (test steps):

1- Click on "ANZEIGE ERSTELLEN" button
2- Fill the form
3- click on "ZURÜCK"

- **Expected results:** You will come back to the homepage and the AD aren't saved.
- **Actual results:** By clicking on the "ZURÜCK" Button on the bottom of the page, nothing happens.

Error Attachement_

![Image](https://user-images.githubusercontent.com/117288240/205856385-57d2b54f-5741-43a2-b8e0-408c0b03c5a7.png)

**Comment by akrguda** [comment]
There is a second ticket about the same topic. We got to discuss / describe it in detail.

https://github.com/AkrosAG/Akros-Marketplace/issues/111

**Comment by LanaKast** [comment]
Test & Testprotokoll needs to be carried out for this ticket @sereno77 , thank you :)

**Comment by sereno77** [comment]
Sereno, 17.11.2022: This ticket is also part of the test case in ticket 111.  Testing done, test document done, Test passed / ok

**Comment by TimmyAeberli** [comment]
Okayed by PO
