### ISSUE TITLE
Eliminate part of the software (selectable items) that are not part of the february 2023 version

### ISSUE THREAD

**Issue by akrguda** [AkrosAG/Akros-Marketplace#262]
As PO I want that the visible / selectable softwareparts (application) is defined for the "february 2023" version and all parts, that will not be done anymore are disabled in the software / frontend so a user can just click on items which are in use and has some function part in the software. 

**DoR:** 

- [x] The part about the software that will not be done is known and documented

**Aca:**

- [x] Aca1: The changes to be done are documented in this ticket
- [x] Aca2: The documented part of the software, that is not in use, is not visible / selectable anymore. Those values can not be selected anymore

**DoD:**

- [x] The visible / selectable part in the application fits the target definitions for february 2023
- [x] The scope of work is visible and clear and no items / button exists anymore, that are not in use and will not be in use in the future

**Comment by akrguda** [comment]
Following the information about the part that should be eliminated:

1. Eliminate "Mitfahrgelegenheit" selection:


![Image](https://user-images.githubusercontent.com/105440971/207641593-b8fde7f2-feba-4275-809c-3b97b16f66f4.png)

2. If it is not to difficult also remove the selection what was created for search "Mitfahrgelegenheiten":



![Image](https://user-images.githubusercontent.com/105440971/207641899-3b9f5dc6-f0af-485a-9307-cec5c3cef93c.png)


3. Insert a new ad: Eliminate the selection "car sharing"


![Image](https://user-images.githubusercontent.com/105440971/207642049-19fe0b2f-bd90-49d7-92c5-b8b2f059643d.png)

4. Because there is not other value to chose, set the only selectable value as default



![Image](https://user-images.githubusercontent.com/105440971/207642721-0bcb78b7-5dcd-48ff-b63e-9416721ed7bd.png)


5. There is one page that was shown up when "car sharing" was selected. If possible, eliminate this page (or it can not be selected anymore. 



![Image](https://user-images.githubusercontent.com/105440971/207642954-5e0372eb-419e-40a3-a703-fcc3e321ff6b.png)

**Comment by akrguda** [comment]
Sereno, 22.12.2022: Testing done, all tests passed / ok.

**Comment by TimmyAeberli** [comment]
okayed by PO
