### ISSUE TITLE
PNG image format is not supported during upload

### ISSUE THREAD

**Issue by balsih** [AkrosAG/Akros-Marketplace#289]
Test Summary: After Uploading PNG format image, "Alle Anzeige/Advertisments are not shown"

Test browser: Firefox

Test Steps

1. Go to the Site and click to "eine Anzeige erstellen/Create new Advertisement"
2. New "Anzeige" will appear in the same page
3. Fill all the requirements of the asked fields
4. Upload Pictures in PNG format
5. Click to "Veröffenlich"

Result: All earlier published advertisements are no more available

![Image](https://user-images.githubusercontent.com/117288240/212926015-2d25c3b6-3c18-4daf-9a49-efee04471feb.png)

**Comment by TimmyAeberli** [comment]
@Atanasov-AA  Spike time-boxed 4-8h

**Comment by Atanasov-AA** [comment]
I don't think there is a bug with uploading png images. There were some wrong latitude/longitude entries in the database, I fix them and now I can't reproduce it. @balsih can you please try to reproduce it again if it's still a problem, please contact me.

**Comment by balsih** [comment]
@Dummylearners this was the ticket that you initially created as a draft and I converted it into an issue ;-)

**Comment by Dummylearners** [comment]
Retested ticket

Test environment: Firefox browser
Test OS: windows

Test Steps to reproduce issue

1.     Go to the Site and click to "eine Anzeige erstellen/Create new Advertisement"
2.     New "Anzeige" will appear in the same page
3.     Fill all the requirements of the asked fields
4.     Upload Pictures in PNG format
5.     Click to "Veröffenlich"

Test PASS

- Expected Test Result: apart from PNG image format may accept the site while uploading and publishing the advertisement.
- Test result matches the expected result.

Screenshots:
<img width="192" alt="01 02Parkplatz" src="https://user-images.githubusercontent.com/117288240/216178888-9f6c11ca-2024-4663-9826-6cebb24a9ecd.png">

![image](https://user-images.githubusercontent.com/117288240/216178259-98ca1819-8845-47dc-9e7d-518561915bb6.png)

**Comment by Dummylearners** [comment]
Thanks @balsih ;)

Wow!! @Atanasov-AA, you have solved the problem :)

**Comment by Dummylearners** [comment]
![image](https://user-images.githubusercontent.com/117288240/216185118-899233c6-d0f5-4bf7-8c88-5a6503f110e2.png)

Published one more Parkplatz advertisement with PNG and JPG images:-

Results are as expected!
- JPG and PNG formatted images are uploaded
- Also Shows search result under Parkplatz
- All uploaded images are uploaded and on display after publishing.

**tested by Anupama/ retested on 01.02.2023/ Test PASS/ Test document is updated**
@LanaKast @TimmyAeberli @balsih @Atanasov-AA

**Comment by Dummylearners** [comment]
Re tested and checked, All OK.
Changes in Data base give the 100% expected results.

1. All "Suche" results type (Zimmer, Wohnung, Haus, Parkplatz) are working as expected.
2. All "Alle Anzeige" result type (Zimmer, Wohnung, Haus, Parkplatz) are working as expected.
3. All earlier published advertisements are available after clicking "search" button
4. All Ads are published with newly published advertisements.
5. There is no more occurrence of site crash. (as in case of [#222](https://github.com/AkrosAG/Akros-Marketplace/issues/222))

@LanaKast @Atanasov-AA
