### ISSUE TITLE
Homepage "Alle Anzeige/All advertisements" does not work anymore

### ISSUE THREAD

**Issue by Dummylearners** [AkrosAG/Akros-Marketplace#291]

**Comment by Dummylearners** [comment]
**This is the cause of uploading wrong image file format during "Eine Anzeige Erstellen/ Add an Advertisement"
Site allows the wrong file format to upload without any restriction.**

This Ticket is created after testing #257 

Test Environment: Firefox Web browser
Test OS: Windows

Test case 1
Test steps

Open Site
Under Unterkünfte/Accommodations, click Angebote (is auto selected)
Choose Haus/house
Click to Eine Anzeige Erstellen/ create an Advertisement button
Look for search result in next page

Pre-condition: Advertisement is already created
Post result: No Advertisement is on display

Test Fail

Test case 2
Test steps

Open Site
Under Unterkünfte/Accommodations, click Anfragen/Inquiry 
Choose Haus/house
Click to Eine Anzeige Erstellen/ create an Advertisement button
Look for search result in next page

Pre-condition: Advertisement is already created
Post result: No Advertisement is on display

Test Fail

Screenshots of test case1:
![Image](https://user-images.githubusercontent.com/117288240/213527202-1a254d34-ed98-4bed-85eb-d0136e916dfa.png)



![Image](https://user-images.githubusercontent.com/117288240/213527416-d51fbd0a-e4b1-49bb-b4d0-385a8c8bf94a.png)

**Comment by LanaKast** [comment]
Reference #222

**Comment by Dummylearners** [comment]
@asiday @LanaKast

Repeated given solution steps from #222
Result is not the same as expected.

-     Search for all topics and find the ID number of your topic. > Where to search and find ID?
-     "Delete your topic using the ID >"Topic ID is 0 in Red?

Please check, if any step is missed out. Thanks

Screenshot 1.
userID-0
Screenshot 2.
image

**Comment by Dummylearners** [comment]
https://user-images.githubusercontent.com/117288240/214452358-995ea8cc-5961-461c-97db-0819cc063a4c.png
https://user-images.githubusercontent.com/117288240/214452720-c2f21e62-f810-424a-991f-f507a91a9223.png

**Comment by Dummylearners** [comment]
False Topic Ids are deleted with false image formatted.

Now "Alle Anzeige/All advertisements" are working.
@asiday. Thanks 
@LanaKast

**Comment by Dummylearners** [comment]
Repeat test steps to reproduce the pass results.

Anupama/Test Pass/ Test document updated/ 25.01.2023

**Comment by Atanasov-AA** [comment]
There is a bug in the backend, sometimes the latitude and longitude are not set and that leads to a crash in the frontend.

**Comment by Atanasov-AA** [comment]
@Dummylearners can you, please test again, now it should be fixed.

**Comment by Dummylearners** [comment]
Now after clicking to "Alle Anzeige" all accommodation type of searches are working.

Observation: They all show same numbers in search results, that is 21. Thanks

@LanaKast @TimmyAeberli @Atanasov-AA 


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/guptan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/guptan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



Search   Type | Login | Without login
-- | -- | --
Zimmer | 21 | 21
Zimmer   Mobilierts | 21 | 21
Wohnung | 21 | 21
Wohnung   mobiliert | 21 | 21
Haus | 21 | 21
Haus mobiliert | 21 | 21
Parking | 21 | 21
Total | 147 | 147



</body>

</html>

**Comment by TimmyAeberli** [comment]
okayed by PO
