### ISSUE TITLE
No more search result of Apartment is working after creating and publishing new Advertisment

### ISSUE THREAD

**Issue by Dummylearners** [AkrosAG/Akros-Marketplace#294]
From home page after creating and publishing an Advertisement" eine Anzeige erstellen von Wohnung" for an Apartment, no search result is working.

This bug is similar to #222

Problem occurred again. The cause is this time not unsupported format of uploaded picture for a new add. Image file format is .jpg. Same 3 images were uploaded for both upload image criteria.

Test Environment: Firefox Web browser
Test OS: Windows

Test Steps

1. From home page, click to create a new Advertisement/Eine Anzeige erstellen
2. Click I offer/ich Biete 
3. Under art of Angebote select Wohnung/Apartment and other all fields should be filled
4. Upload the Main Photo in JPG format
5. Upload rest other photos in JPG Format
6. See Preview, check if you want to make changes, click to Back button/Zurück for any changes.
7. Click to Publish the advertisement// öffentlich
8. Go back to Home page
9. Select Wohnung/Apartment
10. Click the Search/Suche to get the result

Test Fail

Precondition: Under “Create new Apartment” Ich biete/I offer criteria should be fulfilled.
Expected Result: Created Advertisement for Apartment, published publicly
Actual result/ Post Test Result: Created Advertisement after published failed to give results for Apartment 

Screenshot of test result:

![Image](https://user-images.githubusercontent.com/117288240/213579901-8ceffc44-722b-451c-bd49-121473083966.png)

**Comment by Dummylearners** [comment]
Anupama/ Tested/ Test Fail/ Test document updated on 20.01.2023

**Comment by Dummylearners** [comment]
[Create ad: cover image#52](https://github.com/AkrosAG/Akros-Marketplace/issues/52) This similar bug/issue to this Ticket #294

**Comment by LanaKast** [comment]
#285 wurde gelöst, somit kann dieses Ticket abgeschlossen werden

**Comment by TimmyAeberli** [comment]
okayed by PO
