### ISSUE TITLE
Design API (Basic structure and Methods)

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#6]
**Story:** as a developer I want to have API in order to access the EndPoint.

EndPoints:
 - get category
 - get category fields
 - search
 - create / modify /delete ad

- [x] Create Typescript definition of User Object
- [x] (TA)  Decide on  Methods to be used
- [x]  (TA) Define all endpoints and business objects together with the PO/BA in the api.yaml file
- [x] (CA) According to the API Design the Backend need to be adapted
- [x] Client and Server STUB get generated
- [x] (CA) Frontend adaptation to backend changes as consequence of API and model changes

**_AC1_**: all methods are callable via Endpoints
**_AC2_**: API is documented according to OpenAPI standard and Arc42

**Comment by TimmyAeberli** [comment]
Methods and API Endpoints checked with Swagger.
