### ISSUE TITLE
Search: accomodation detail view

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#63]
**Story:** As a user I want to get detail view of selected add, in ordert to see all captured information.

Precondition: #88 Design Story should be implemented 

_Acceptance criteria:_

- [x] AC1: all information of the selected add is presenting on one page . For for the fields per subcategory see excel in UI field catalog in https://github.com/AkrosAG/Akros-Marketplace/issues/132
- [x] AC2: all fotos are visible in the detail view on the top -> for the pictures behaviour the additional story #92  and additional AC should check there. Dummy pictures can be used here if the story for upload pictured not implemented.

-------------------------
Example: 

![image](https://user-images.githubusercontent.com/96523998/158338543-3f413f59-e74e-471d-9024-d35c2e4e4773.png)

--------------
DoD
- [x] Story is tested against acceptance criteria
- [x] Unit test should be passed
- [x] Integration test is done ( if applicable)
- [x] Non-functional requirements are met
- [x] Story ok-ed by Product Owner
- [x] Peer Code Review performed
- [x] Any configuration or build changes documented

**Comment by Dummylearners** [comment]
AC1: Pass

Tested in Test environment.

Test Steps
1-Click to "Alle anzeige" button and click one of the Anzeige/advertisement to see the details with photo.




(though, story is not clearly defined. if user wants to see details of Advertisement with Photo after ### clicking"Suche Button" (marked in Pink box) or in "Alle anzeige button" (Masked in Purple box)

Another question, User wants to see all details without log in or after user log in?
I am not sure who will revise the Ticket?, thus I am marking you. Thanks. @LanaKast 


![Image](https://user-images.githubusercontent.com/117288240/210378318-a7ef7b1e-445b-4d3c-a8f9-ee822b667bfd.png)

**Comment by Dummylearners** [comment]
**Expected test result after retesting: there is no any result shown after clicking to "Suche" or "Alle Anzeigen" button.

This may be a server down situation in evenings?**



![Image](https://user-images.githubusercontent.com/117288240/210416371-51badbf4-ed69-4a58-8733-dbb0913cbdd3.png)

**Comment by TimmyAeberli** [comment]
@Dummylearners  you moved this ticket to PO Testing. However, the last comment dates back to 17 days ago, noting that the site is not wokring. 
Could you please update the ticket with your last Testing insights?

**Comment by Dummylearners** [comment]
@TimmyAeberli, site is working and updated. 
@LanaKast, this is ticket is retested.


Tested in Test environment: Firefox Browser
Test OS: Windows

Test Steps

1- Log in the marketplace: https://am-ui.azurewebsites.net/home
2- Click to "Alle Anzeigen" button
3- In page, all searches will appear
4- Click to any Add to preview with detail view and images.

AC1 and AC2: Pass

TEST PASS

Pre-condition: Added accommodation Advertisements should correctly fill in advance.
Excepted result: After clicking to "All View" search should appear. After selecting to one add, the detail view with images should appear.
Post Test Result:  Testing fulfilled both AC 1 and AC criteria.

Screenshots of testing:

![Image](https://user-images.githubusercontent.com/117288240/215785829-0573d2f5-99c7-4b86-ba4f-e4bff9e667c2.png)

**Comment by Dummylearners** [comment]
@TimmyAeberli @LanaKast 

My Observations:- if it is a bug, or it is a field feature?

- Under "Angebote" there are 4 types of Accommodations are available (Zimmer, Wohnung, Haus and Parkplatz)
- The "Zimmer" remains auto selected.
- According to the User story, there is no given any specification about any search of "Zimmer".
- Unterkunft/Accommodation is not specified. If not, in auto select,  "Zimmer" should not be shown in the field.


![Image](https://user-images.githubusercontent.com/117288240/215791887-661be18f-a1df-4b30-ab9a-a03e1ef85411.png)

**Comment by TimmyAeberli** [comment]
okayed by PO
