### ISSUE TITLE
Keycloak

### ISSUE THREAD

**Issue by fingeririna** [AkrosAG/Akros-Marketplace#64]
Analyze how to put on a keycloak for the akros logic.

**Comment by stefanleminh** [comment]
The authentification and authorization for AKROS employees shall be implemented as such:
1. The login functionality will be implemented using Keycloak. For the authentification part of it, any public OAuth2-Client can be used, such as Google [(here](https://keycloakthemes.com/blog/how-to-setup-sign-in-with-google-using-keycloak) and [here](https://cloud.google.com/architecture/identity/keycloak-single-sign-on) ).
2. However, that by itself is not enough for the user to be authorised to use the marketplace - He will have to provide an AKROS-E-Mail. The application will then send a confirmation e-mail for the user to confirm that he is indeed an AKROS employee. Only then will he be allowed to post ads.
