### ISSUE TITLE
Check out ZIP-code related options within Post API

### ISSUE THREAD

**Issue by TimmyAeberli** [AkrosAG/Akros-Marketplace#83]
As a Developer I want to use an API that takes input "center-ZIP-code" and "radius" and returns a list of ZIP-codes within the specified radius around the "center-ZIP-code", in order to relate a request to possible matches.

AC1: The API needs to return ZIP-codes and optionally additional information, like canton or long & lat.
AC2: The API needs to work for Switzerland.
AC3: The API needs to be free or allow for a sufficient amount of free lookups.
AC4: The API should be easy to use and sufficiently "secure".

**Comment by TimmyAeberli** [comment]
I found a decently working API (tested with Postman). However it is only offering 30 free lookups per month. Unlimited lookups cost 9$ per month.
Here is a image of the search and lookup response.
![image](https://user-images.githubusercontent.com/41478805/161928919-951a003a-237b-41ca-a2b5-52291e0770b6.png)

**Comment by stefanleminh** [comment]
How about something like [OpenRouteService](https://openrouteservice.org/dev/#/api-docs/v2/directions/%7Bprofile%7D/get) or [Graphhopper](https://docs.graphhopper.com/#tag/Matrix-API)? Their pricing seems fair even for free tiers since they're based on the free OpenStreetMaps.

**Comment by TimmyAeberli** [comment]
Great call. Both services offer **Isochrones** ([definition](https://en.wikipedia.org/wiki/Isochrone_map)), which would allow us to shift from Radius=[Distance] to CommuntingLimit=[Time]. However, I found no way to have a public transport dependent Isochrone (include communting time by train). Isochrones in both services are calculated for automotive transportation.

I did find a app [ÖVExplorer](https://www.oevexplorer.ch/) that allows to do just that: 
![image](https://user-images.githubusercontent.com/41478805/161983009-b80a62c5-15f3-4b76-8337-0f2b0f9d4d54.png)

ACTUAL PROPOSED SOLUTION: I then searched for a API that has a Isochrone ZIP Code filter and found this with ([Traveltime](https://docs.traveltime.com/api/reference/postcode-search)), I got an API-key [they offer 1000 requests per month](https://docs.traveltime.com/api/overview/getting-keys). And Switzerland is a supported country, so I checked the approximate accuracy: It seems to be fairly accurate. However, we only get longitude & latitude in the response and would then have to calculate the ZIP codes within that shape like [this](https://stackoverflow.com/questions/45027968/check-if-pointlat-lng-inside-a-shape-without-javascript). @stefanleminh do you think that is feasible? I doubt it.

alternatively, we could use maybe ([Mapnificent](https://www.mapnificent.net/switzerland/#16/47.3669/8.5466/600/47.3630/8.5487)), ([also on github](https://github.com/mapnificent/mapnificent))

We could also use it in a later stage for display in maps, when browsing the appartments listed.
Additionally it is worth noting, that we can use https://developer.post.ch/en/address-web-services-rest for address-verification (at a later stage).

**Comment by stefanleminh** [comment]
I think we should go with the solution that is the easiest to implement - The distance doesn't have to be exact. I think it doesn't even matter too much whether it's direct distance or by public transport. You usually just want to know if it's within the general area of the radius and public transport can change for people.

**Comment by TimmyAeberli** [comment]
I contacted https://ezcmd.com/world-postal-codes (first comment and screenshot) for a free API-key for non-commercial use. However, until then we might work with the 190 calls per month. It should be sufficient for our use. And if we get to that limit, at that point it might be worth paying 9$ a month, since it indicates that Marketplace is widely used by AKROS employees.

**Comment by stefanleminh** [comment]
Looking at [OpenRouteService](https://openrouteservice.org/dev/#/api-docs/v2/directions/%7Bprofile%7D/get), maybe a solution could be:
1. Convert the given ZIP code from the search into coordinates with the [Geocode API](https://openrouteservice.org/dev/#/api-docs/geocode/search/get)
2. Convert the adresses of each result into coordinates with the [Geocode API](https://openrouteservice.org/dev/#/api-docs/geocode/search/get)
    -  I wonder if we should do do the conversion when we create ads and save the coordinates in the DB so we wouldn't have to make requests to the API for each search request - Then again the API has up to 2000 **daily** requests so 2we should be fine.

4. Calculate the distance between the ZIP-Code from 1 with each result with the [Directions API](https://openrouteservice.org/dev/#/api-docs/v2/directions/%7Bprofile%7D/post)
5. Filter out any result that is not within the distance given from the search.
